version: 3
vars:
  codegenJar: "../rmf-codegen/rmf-codegen.jar"
  apiSpecsDir: "../commercetools-api-reference/api-specs"
  generatedDir: "./generated"
  versionId: 1.3.0

tasks:
  install:
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  test:
    cmds:
      - go test ./...

  fmt:
    cmds:
      - go fmt ./...

  coverage:
    cmds:
      - go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg=./... ./...
      - go tool cover -html=coverage.txt

  generate:
    cmds:
      - task: generate-checkout
      - task: generate-connect
      - task: generate-importapi
      - task: generate-frontend
      - task: generate-ml
      - task: generate-platform

  generate-checkout:
    cmds:
      - task: generate-api
        vars: {apiName: checkout, path: checkout}

  generate-connect:
    cmds:
      - task: generate-api
        vars: {apiName: connect, path: connect}

  generate-importapi:
    cmds:
      - task: generate-api
        vars: {apiName: importapi, path: importapi}

  generate-frontend:
    cmds:
      - task: generate-api
        vars: {apiName: frontend, path: frontend-api}

  generate-ml:
    cmds:
      - task: generate-api
        vars: {apiName: ml, path: ml}

  generate-platform:
    cmds:
      - task: generate-api
        vars: {apiName: platform, path: api}

  generate-api:
    cmds:
      - java -jar {{ .codegenJar }} generate {{ .apiSpecsDir }}/{{ .path }}/api.raml -b {{ .apiName }} -o {{ .generatedDir }}/ -t GO_CLIENT
      - goimports -w {{ .generatedDir }}/{{ .apiName }}/
      - go fmt {{ .generatedDir }}/{{ .apiName }}/
      - rm -rf {{ .apiName }}/
      - mv {{ .generatedDir }}/{{ .apiName }} .
      - perl -p -i -e 's/const Version = "1.0.1"/const Version = "{{ .versionId }}"/' {{ .apiName }}/client.go

